---
- name: Install pre requisites
  become: true
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python-setuptools
    - make

- name: Install docker
  become: true
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  
- name: Add deb repo
  become: true
  command: touch /etc/apt/sources.list.d/docker.list
  
- lineinfile: dest="/etc/apt/sources.list.d/docker.list" line="{{item}}"
  become: true
  with_items:
    - "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"

- name: apt update
  become: true
  apt: update_cache=yes

- apt: name=docker-ce state=present
  become: true

- name: Add user mod
  become: true
  command: usermod -aG docker ubuntu
