---
- name: Check if "Swarm Mode" is enabled.
  shell: docker info
  changed_when: False
  register: docker_info
  tags:
   - skip_ansible_lint
   
- name:  Init "Swarm Mode" on the manager
  shell: docker swarm init | grep "docker swarm join "
  register: docker_worker_command
  tags:
   - skip_ansible_lint # Suppressing the linter

- name: Join the pending Swarm worker nodes.
  shell: "{{ docker_worker_command }}"
  changed_when: False
  when: "docker_info.stdout.find('Swarm: active') == -1
    and docker_info.stdout.find('Swarm: pending') == -1
  tags:
    - skip_ansible_lint # Suppressing the linter
